### ISSUE TITLE
problems authenticating

### ISSUE THREAD

**Issue by onestep749** [henesy/disco#20]
Hi, i am unable to authenticate myself with this, some information: ...

% go version
go version go1.15.3 linux/amd64
% uname -a 
Linux issss95.home 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux

I am using auth=pass, and have verified the information is correct. 

Connecting...2020/10/24 18:16:39 Session Failed
2020/10/24 18:16:39 Unable to fetch discord authentication token. <nil>

**Comment by brightersun99** [comment]
i see there is an identical issue open, close please
